### ISSUE TITLE
Criar a 1a. nota de release

### ISSUE THREAD

**Issue by armandossrecife** [my-prototypes/tflk#2]
Foi criada a primeira nota de release para permitir testes junto ao primeiro protótipo de demonstração da aplicação. 

https://github.com/my-prototypes/tflk/releases/tag/0.1

**Comment by armandossrecife** [comment]
Fiz os testes em uma máquina virtual Lubuntu 22.04 (usando o Virtual Box) e os testes unitários e os testes de sistema passaram (seguindo as orientações da nota de release).

**Comment by Mathwebb** [comment]
Executei os testes na minha máquina local Windows 11 22H2 seguindo todas as orientações da release, os testes unitários passaram, mas nos testes de sistema teve uma falha no teste de login de usuário válido:

FAIL: test_login_usuario_valido (app.tests.system_tests.CT_TS_01.TestLoginFeature)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mathe\Downloads\Teste tag 0.1\tflk-0.1\app\tests\system_tests\CT_TS_01.py", line 40, in test_login_usuario_valido
    self.assertIn("dashboard", self.driver.current_url)  # Substitua "PÁGINA_DE_DESTINO" pela URL da página para onde o login deve redirecionar
AssertionError: 'dashboard' not found in 'http://localhost:5000/login'

----------------------------------------------------------------------
Ran 2 tests in 10.950s

FAILED (failures=1)

**Comment by armandossrecife** [comment]
Olá Matheus, obrigado pelo feedback. Mas esta versão 0.1 **não suporta windows**, pois é preciso generalizar o tratamento de diretórios para usar o separador / ou \  Com isso, essa versão só funciona em ambiente Linux ou MacOS. 

5. Known Issues
A aplicação ainda não usa ORM para acessar o banco.
Ainda não foi implementado o upload de imagens
**Esta aplicação foi prioritariamente projetada para executar em ambiente Linux ou MacOS.**

Em um momento oportuno vou fazer os ajustes necessários para a aplicação funcionar em ambiente Windows, Linux e MacOS. 

Para esta versão 0.1, você consegue testar em um ambiente Linux?

**Comment by Mathwebb** [comment]
Consigo sim, só que deve demorar um pouco mais para eu conseguir dar o feedback

**Comment by armandossrecife** [comment]
Você pode testar a aplicação via [Codespaces](https://github.com/features/codespaces)

1. Carregue o repositório principal (https://github.com/my-prototypes/tflk)
2. Clique no botão "Code"
3. Selecione a aba "Codespaces"
4. Clique no botão "Create codespace on main"
5. Deverá ser carregado o ambiente padrão do Visual Studio Code
6. Siga os passos do "Ambiente de Desenvolvimento" para executar a aplicação
7. O ambiente do Codespace vai pedir para você abrir uma nova janela do browser
8. Deverá aparecer a tela "Home Pública para Testes"

**Comment by Mathwebb** [comment]
Professor, eu tentei rodar os testes no codespaces do GitHub, mas o selenium não estava funcionando devido a ausência do Mozilla Firefox, tentei instalar via terminal, mas não consegui. Então, executei a aplicação em uma máquina virtual Ubuntu 22.04.2 LTS (usando o WSL - Windows Subsystem for Linux), seguindo as orientações da release. Eu não sei se eu fiz algo de errado, os testes unitários passaram, mas teve um teste de sistema que falhou:

FAIL: test_login_usuario_valido (app.tests.system_tests.CT_TS_01.TestLoginFeature)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mathwebb/downloads/tflk-0.1/app/tests/system_tests/CT_TS_01.py", line 40, in test_login_usuario_valido
    self.assertIn("dashboard", self.driver.current_url)  # Substitua "PÁGINA_DE_DESTINO" pela URL da página para onde o login deve redirecionar
AssertionError: 'dashboard' not found in 'http://localhost:5000/login'

----------------------------------------------------------------------
Ran 2 tests in 2.038s

FAILED (failures=1)

**Comment by armandossrecife** [comment]
Olá Matheus, vou fechar este issue, pois o ambiente de testes tem que ter o Firefox instalado e com permissão para execução. 

Para rodar em uma máquina virtual Linux é preciso garantir que ela tenha o Firefox instalado e com permissão para execução do usuário corrente.

**Comment by armandossrecife** [comment]
Obs: Não funciona no code space, pois ele não tem o Firefox instalado e configurado com permissão para executar na chamada do browser corrente do usuário.
